title: "How to create a blog in Laravel with Filament admin panel?"

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Laravel 10 blog with Filament admin panel.
  The goal of this repository is to showcase good Laravel development practices with a simple application.

# Build settings

theme: minima

# header_pages:
#   - about.md
